import C from "./colors";

// Services that get a "stories" multiplier (ground-level services don't)
export const SERVICES_WITH_STORIES = [
  "pressure_washing",
  "window_cleaning",
  "roof_cleaning",
  "gutter_cleaning",
  "gutter_guard_install",
];

const DEFAULT_CONFIG = {
  businessName: "CleanBid",
  adminPassword: "admin123",
  globalPriceAdjustment: 0,
  googlePlacesApiKey: "",
  leadSources: [
    "Online Organic",
    "Online Paid",
    "Social Media",
    "Yard Signs / Vehicles",
    "Repeat / Referral",
    "Direct Mail",
    "Doorknocking",
    "Events",
    "Sales Team",
    "Other",
  ],
  services: [
    {
      id: "pressure_washing",
      name: "Pressure Washing",
      icon: "\u{1F4A6}",
      description: "Driveways, sidewalks, patios & siding",
      basePrice: 150,
      perSqFt: 0.15,
      perWindow: 0,
      perLinFt: 0,
      enabled: true,
      extras: [
        { id: "siding", label: "House Siding", price: 120 },
        { id: "patio", label: "Patio / Porch", price: 75 },
        { id: "fence", label: "Fence", price: 90 },
      ],
    },
    {
      id: "window_cleaning",
      name: "Window Cleaning",
      icon: "\u{1FA9F}",
      description: "Interior & exterior window washing",
      basePrice: 0,
      perSqFt: 0,
      perWindow: 8,
      perLinFt: 0,
      enabled: true,
      // Wisconsin avg: ~1 window per 80 sq ft of living space
      windowsPerSqFt: 0.0125,
      windowTypes: [
        { id: "casement", label: "Casement", multiplier: 1.0, icon: "\u{1FA9F}", description: "Standard hinged windows" },
        { id: "double_hung", label: "Double Hung", multiplier: 1.6, icon: "\u{1FA9F}", description: "Two sliding sashes (+60%)" },
        { id: "combination", label: "Combination / Storm", pricePerWindow: 40, icon: "\u{1FA9F}", description: "Storm windows ($40/window)" },
      ],
      extras: [
        { id: "screens", label: "Screen Cleaning", price: 3 },
        { id: "tracks", label: "Track & Sill Detail", price: 2 },
        { id: "skylights", label: "Skylights", price: 25 },
      ],
    },
    {
      id: "deck_cleaning",
      name: "Deck Cleaning",
      icon: "\u{1FAB5}",
      description: "Wood & composite deck restoration",
      basePrice: 175,
      perSqFt: 0.25,
      perWindow: 0,
      perLinFt: 0,
      enabled: true,
      extras: [
        { id: "stain", label: "Staining / Sealing", price: 250 },
        { id: "railings", label: "Railing Detail Clean", price: 65 },
        { id: "stairs", label: "Stairs (per flight)", price: 45 },
      ],
    },
    {
      id: "concrete_cleaning",
      name: "Concrete Cleaning",
      icon: "\u{1F9F1}",
      description: "Driveways, garage floors & walkways",
      basePrice: 125,
      perSqFt: 0.12,
      perWindow: 0,
      perLinFt: 0,
      enabled: true,
      extras: [
        { id: "sealing", label: "Concrete Sealing", price: 200 },
        { id: "oil_stain", label: "Oil Stain Removal", price: 50 },
        { id: "edging", label: "Edging & Detail Work", price: 40 },
      ],
    },
    {
      id: "roof_cleaning",
      name: "Roof Cleaning",
      icon: "\u{1F3E0}",
      description: "Soft wash moss & algae removal",
      basePrice: 250,
      perSqFt: 0.18,
      perWindow: 0,
      perLinFt: 0,
      enabled: true,
      extras: [
        { id: "moss_treatment", label: "Moss Prevention Treatment", price: 150 },
        { id: "chimney", label: "Chimney Wash", price: 75 },
        { id: "solar_panels", label: "Solar Panel Cleaning", price: 100 },
      ],
    },
    {
      id: "gutter_cleaning",
      name: "Gutter Cleaning",
      icon: "\u{1F327}\u{FE0F}",
      description: "Gutter flush, downspout clearing",
      basePrice: 125,
      perSqFt: 0,
      perWindow: 0,
      perLinFt: 1.5,
      enabled: true,
      conditionQuestions: [
        { id: "plugged_downspouts", label: "Are any downspouts plugged?", priceAdj: 35 },
        { id: "trees_growing", label: "Trees or debris growing out of gutters?", priceAdj: 50 },
        { id: "has_gutter_guards", label: "Do you have existing gutter guards?", priceAdj: 25 },
      ],
      extras: [
        { id: "downspout", label: "Downspout Repair", price: 45 },
        { id: "whitening", label: "Gutter Whitening", price: 120 },
      ],
    },
    {
      id: "gutter_guard_install",
      name: "Gutter Guard Installation",
      icon: "\u{1F6E1}\u{FE0F}",
      description: "Professional gutter guard installation — priced per linear foot",
      basePrice: 0,
      perSqFt: 0,
      perWindow: 0,
      perLinFt: 14.99,
      enabled: true,
      tiers: [
        { id: "basic", label: "Basic Install", perLinFt: 14.99, description: "Guard installation only" },
        { id: "with_cleaning", label: "Install + Gutter Cleaning", perLinFt: 19.99, description: "Includes full gutter cleaning before install" },
        { id: "full_service", label: "Full Service", perLinFt: 24.99, description: "Gutter cleaning, guard install & downspout work" },
      ],
      extras: [],
    },
  ],
  packages: {
    basic: {
      label: "Basic",
      multiplier: 1.0,
      color: C.textMid,
      tag: "Just the essentials",
      features: ["Service completion", "Standard cleaning", "Basic cleanup"],
    },
    standard: {
      label: "Standard",
      multiplier: 1.35,
      color: C.primary,
      tag: "Most Popular",
      popular: true,
      features: [
        "Everything in Basic",
        "Deep clean treatment",
        "Before/after photos",
        "Spot re-treatment guarantee",
      ],
    },
    premium: {
      label: "Premium",
      multiplier: 1.75,
      color: C.accent,
      tag: "The Full Treatment",
      features: [
        "Everything in Standard",
        "Premium-grade products",
        "Full property inspection",
        "Priority scheduling",
        "60-day satisfaction guarantee",
      ],
    },
  },
  bundleDiscounts: { 2: 5, 3: 10 },
  seasonalBundles: [
    {
      id: "spring_refresh",
      name: "Spring Refresh Bundle",
      services: ["pressure_washing", "window_cleaning", "gutter_cleaning"],
      discount: 15,
      active: true,
      endDate: "2026-05-31",
      tagline: "Get your home spring-ready!",
    },
  ],
  marketing: {
    showUrgencyTimer: true,
    urgencyMessage: "Spring booking slots filling fast!",
    urgencyEndDate: "2026-04-15",
    showSocialProof: true,
    socialProofCount: 47,
    showLimitedOffer: true,
    limitedOfferText: "Book this week & get a FREE gutter inspection",
    showReviewBadge: true,
    reviewCount: 238,
    reviewAverage: 4.9,
  },
  followUp: {
    enabled: true,
    sequences: [
      {
        id: "1",
        delay: "Immediate",
        type: "email",
        subject: "Your Custom Quote from {{business}}",
        body: "Hi {{name}},\n\nThank you for requesting a quote!\n\nTotal: {{total}}\n\nReady to book? Reply or call us!",
        active: true,
      },
      {
        id: "2",
        delay: "2 days",
        type: "sms",
        subject: "",
        body: "Hi {{name}}! Checking in on your {{services}} quote for {{total}}. Questions? Reply here!",
        active: true,
      },
      {
        id: "3",
        delay: "5 days",
        type: "email",
        subject: "Still thinking it over?",
        body: "Hi {{name}},\n\nSpots filling up!\n\nYour quote: {{total}}\n\nBook now to lock in your price.",
        active: true,
      },
      {
        id: "4",
        delay: "14 days",
        type: "email",
        subject: "We miss you, {{name}}!",
        body: "Prices may change soon!\n\nQuote: {{total}}",
        active: false,
      },
    ],
  },
};

export default DEFAULT_CONFIG;
